The Next Web Clone
kunmi02/TNW pull request #5
Opened 2020-10-29 15:45 UTC by kunmi02

The is a website clone of the next web. We worked on 2 breakpoints which are 768px and 1024px.

2020-10-29 18:06 UTC, uryelah requested changes
Hi **Akshay Narkar**, I'm Sarah your reviewer for this PR 👩‍🚀 

You did a great job building the small and medium views of this project, the attention to the hover effects and typography was especially good, but it seems that the project layout is breaking if viewed on bigger screens than ~1030px.

Read the review comments below carefully and take some time to compare your clone with the [original page](https://thenextweb.com/), using your browser responsiveness tools, and then get to coding! You are really close, just really need to fix the large windows layout issue.

If you think you need a refresher about how to use responsiveness tools I'd check [this Firefox, the best browser for developers, turorial](https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode).

> Note: It seems that this project was submitted only by Akshay and marked as 'I worked alone on this project' even though it seems like two people built it. If this was by mistake make sure to contact student success to make sure both of you get the correct status for this project completion.

Rock on! 🎸 👨‍🎤 

# Required Changes 🏗️ 🐛 💡

-----

 **Kindly fix the pointed out items and comments below before requesting the next code review**

- [ ] Write your next [commit messages following the best practices](https://chris.beams.io/posts/git-commit/), by capitalizing them and writing them in the present/imperative.

- [ ] The page body is not taking the full width of the window. Make sure your clone also shows up properly on large screens, >1024px, with 100% width. Check how in the screenshot two points below there's a white margin at the right side of it.

- [ ] Make sure also that the page layout is also the same on the large screens:
  - Having the TNW logo and a red-ish gradient over the main article's image from the 3 articles at the top.
  - Having the 'Latest Funding' section showing 4 articles in the same row.
  - Having the 'Categories (Apps, Gear, Tech, etc)' section aligning 3 boxes per row.
  - The two smaller articles at the top of the page should be aligned top and bottom with the bigger one, the two smaller ones should have the same height.

**Compare the origin site on larger screens and your clone in the screenshots below:**

 <table style="width:100%">
  <tr>
    <th>Original Page</th>
    <th>Clone</th>
  </tr>
  <tr>
    <td valign="top"><img src=https://user-images.githubusercontent.com/16193212/97612102-bd631000-19f5-11eb-9313-05a61cb79723.jpg /></td>
    <td><img src=https://user-images.githubusercontent.com/16193212/97612126-c653e180-19f5-11eb-820d-1bc67e99c4f0.jpg /></td>
  </tr>
</table> 

- [NOTE] If you are having issues with your media specific CSS files right now try to use media queries to make the site responsive instead. [Check this W3Schools article on media queries.](https://www.w3schools.com/css/css_rwd_mediaqueries.asp)

- [ ] Instead of repeating styles between the 3 stylesheets, for example: `font-family: ARS Maquette, Helvetica Neue, Arial, sans-serif;`, just set those styles common to all of the sizes in one main CSS. Try to avoid repetition, in general, to keep a DRY CSS code and have lighter stylesheet files that load faster.


- [ ] [OPTIONAL] Let's add some box-shadow under the fixed top navbar to make it look closer to the original one and make it 'pop' in the eye by giving it some depth.


------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-10-29 18:06 UTC, uryelah commented on index.html
> +      </footer>
- [x] [OPTIONAL] Ideally the `<footer>` tag will be outside the `<main>` tag. The `<main>` tag should contain the main content, the focus, of the page, the footer is usually not the main content of a webpage. Read more about semantic tags and their meaning [here](https://www.w3schools.com/html/html5_semantic_elements.asp).

2020-10-29 18:06 UTC, uryelah commented on css768.css
> +  font-family: ARS Maquette, Helvetica Neue, Arial, sans-serif;
- [x] Let's avoid repetition and keep the styles that stay constant for the body in just the general CSS file, no need to repeat it for each screen size.

2020-10-29 18:06 UTC, uryelah commented on css1024.css
> +  height: 300px;
- [ ] For the bigger than 1024px screens this height should change to accommodate the growth of image1.

2020-10-29 18:06 UTC, uryelah commented on css1024.css
> +  max-width: 1024px;
- [ ] Is this really necessary? Why don't you just make the body that 100% of the page regardless of it's size in the main CSS file? 
Ex:
`max-width: 100vw`
Try to write styles that require the least amount of changes to be responsive, that will make your CSS files lighter.

2020-10-29 21:50 UTC, MuriloRoque requested changes
## Status: Changes requested :red_circle: 

### Hello @kunmi02 and @akshay-narkar :wave: 

### Thank you for making some of the requested changes, but we still need to improve on some aspects. Please check my suggestions below based on the last review:

- [x] Please update your Live Link every time you make a change to your project, OR even better: when you paste your `index.html` file link there, take the second generated link to the right, it auto-updates as you make the changes (takes some minutes tho)!

- [ ] In your first three articles, please increase the font-size of what's written there, decrease the height of your images and align them, and add the TNW logo, just like in the original.

- [ ] In your 'Latest Funding' section on Large Screens, you are currently displaying only 3 articles, whilst in the original, there are 4 articles.

- [ ] In your Categories section on Large Screens, you are currently displaying only 1 article per row, whilst in the original, there are 3 articles per row.

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-10-30 16:36 UTC, uryelah approved these changes
Hi **Azeez Azeez & Akshay Narkar**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job adding that large screen responsiveness!

You now have the minimum required to continue to the next project, but before that make sure to check the optional suggestions left below, they'll make your site look more professional and hopefully improve your CSS abilities at that.
You can work on them in your spare time or just look up the suggestions for learning's sake.

Good luck with your next HTML&CSS projects! 🚀  

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---------

### Optional suggestions

- [ ] [OPTIONAL] Let's fix that overlapping text over the image on medium to smaller screens. That makes your page look amatourish and decreases how accessible and easy to read the text is if someone has vision problems. 
>Tip: Add a [`min-height` property](https://css-tricks.com/almanac/properties/m/min-height/) to the divs with class `.hardfork-latest` in such way that their minimum height is the height of the image they contain in the right.

![Screenshot_2020-10-30 TNW](https://user-images.githubusercontent.com/16193212/97731538-04afd600-1ab4-11eb-9502-0bf82f74db6a.png)

- [ ] [OPTIONAL] The gradient logo should take 100% height of the image it's overlapping. 
Change the height property of the `.tnw-overlay` div so it takes the necessary height. 
>TIp: [Use your browser inspector tool to test CSS changes there before actually changing the file directly.](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Debugging_CSS)

 ![Screenshot_2020-10-30 TNW(1)](https://user-images.githubusercontent.com/16193212/97731542-05486c80-1ab4-11eb-9d5c-2a340986eb30.png)

---------

    
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-10-30 22:21 UTC, merged